###
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
    "email": "master@gmail.com",
    "password": "master123"
}

###
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
    "email": "requester@gmail.com",
    "password": "requester123"
}

###
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
    "email": "testea@gmail.com",
    "password": "testea123"
}

###
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
    "name": "Teste A",
    "email": "testea@gmail.com",
    "password": "testea123",
    "role": "REQUESTER"
}

###
GET http://localhost:8080/api/test/test-time
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyYWJjNGQ4Ny1iN2EwLTQ5YzQtYTkzMy02NmY5OTcxNjJjNjQiLCJlbWFpbCI6Im1hc3RlckBnbWFpbC5jb20iLCJyb2xlcyI6WyJNQVNURVIiXSwiaWF0IjoxNzQzOTUyNTIxLCJleHAiOjE3NDQwMzg5MjF9.gnc5fe_sceTCCoh_BDhRTdSeHmYzJ3ON-HTMtRKsvyU
Content-Type: application/json

###
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "user123"
}