# Criar um novo evento
POST http://localhost:8080/api/events
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMzI2ZmRkMS01YmFmLTRkNjUtYmI5Ni1jMTUyZWNmN2Y0NGQiLCJlbWFpbCI6Im1hc3RlckBnbWFpbC5jb20iLCJyb2xlcyI6WyJNQVNURVIiXSwiaWF0IjoxNzQ2Mjk3NTY5LCJleHAiOjE3NDYzODM5Njl9.gAHRysrk-juSliOdLpErY9iCMfWBt_p_SrkN5bVDxIM
Content-Type: application/json

{
  "name": "Evento 2",
  "day": "2025-05-29",
  "startTime": "16:40:00",
  "endTime": "19:50:00",
  "theme": "Tema A",
  "targetAudience": "Público A",
  "mode": "PRESENCIAL",
  "environment": "Auditório",
  "organizer": "Organizador A",
  "resourcesDescription": ["Projetor", "Microfone"],
  "disclosureMethod": "Redes Sociais",
  "relatedSubjects": ["Matemática"],
  "teachingStrategy": "Expositiva",
  "authors": ["Autor A", "Autor B"],
  "courses": ["Course A"],
  "disciplinaryLink": "Disciplina A",
  "location": {
    "name": "Local X",
    "floor": "0"
  },
  "status": "PLANEJADO",
  "administrativeStatus": "NORMAL",
  "priority": "ALTA",
  "cleanupDuration": "PT15M",
  "observation": "Nenhuma"
}


### Criar um novo evento
PUT http://localhost:8080/api/events/d280f00f-cb6c-4125-a137-41d7d6df4ae7
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMzI2ZmRkMS01YmFmLTRkNjUtYmI5Ni1jMTUyZWNmN2Y0NGQiLCJlbWFpbCI6Im1hc3RlckBnbWFpbC5jb20iLCJyb2xlcyI6WyJNQVNURVIiXSwiaWF0IjoxNzQ2Mjk3NTY5LCJleHAiOjE3NDYzODM5Njl9.gAHRysrk-juSliOdLpErY9iCMfWBt_p_SrkN5bVDxIM
Content-Type: application/json

{
  "name": "Evento 3",
  "day": "2025-05-29",
  "startTime": "08:00:00",
  "endTime": "12:00:00",
  "theme": "Tema A",
  "targetAudience": "Público A",
  "mode": "PRESENCIAL",
  "environment": "Auditório",
  "organizer": "Organizador A",
  "resourcesDescription": ["Projetor", "Microfone"],
  "disclosureMethod": "Redes Sociais",
  "relatedSubjects": ["Matemática"],
  "teachingStrategy": "Expositiva",
  "authors": ["Autor A", "Autor B"],
  "courses": ["Course A"],
  "disciplinaryLink": "Disciplina A",
  "location": {
    "name": "Local X",
    "floor": "0"
  },
  "status": "PLANEJADO",
  "administrativeStatus": "NORMAL",
  "priority": "ALTA",
  "cleanupDuration": "PT15M",
  "observation": "Nenhuma"
}

### Buscar evento por ID
GET http://localhost:8080/api/events/3926acf0-5a4e-4001-9560-77fd4531ae71
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyYWJjNGQ4Ny1iN2EwLTQ5YzQtYTkzMy02NmY5OTcxNjJjNjQiLCJlbWFpbCI6Im1hc3RlckBnbWFpbC5jb20iLCJyb2xlcyI6WyJNQVNURVIiXSwiaWF0IjoxNzQzOTYzOTAxLCJleHAiOjE3NDQwNTAzMDF9.SCcn6Hcm415c3PLx0z7eSPQet-HHULiRxbtMPSaYs2A

### Buscar todos os eventos
GET http://localhost:8080/api/events
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyYWJjNGQ4Ny1iN2EwLTQ5YzQtYTkzMy02NmY5OTcxNjJjNjQiLCJlbWFpbCI6Im1hc3RlckBnbWFpbC5jb20iLCJyb2xlcyI6WyJNQVNURVIiXSwiaWF0IjoxNzQzOTYzOTAxLCJleHAiOjE3NDQwNTAzMDF9.SCcn6Hcm415c3PLx0z7eSPQet-HHULiRxbtMPSaYs2A

### Atualizar um evento existente
POST http://localhost:8080/api/events/resolve-update/daf45255-0f70-4968-9ca3-dc2b9a604607
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMzI2ZmRkMS01YmFmLTRkNjUtYmI5Ni1jMTUyZWNmN2Y0NGQiLCJlbWFpbCI6Im1hc3RlckBnbWFpbC5jb20iLCJyb2xlcyI6WyJNQVNURVIiXSwiaWF0IjoxNzQ2MTg5ODA4LCJleHAiOjE3NDYyNzYyMDh9.a9eEbfqZQ2CpjP6O_pXwZHpIM__2irIv5XZ7eGNq_bs
Content-Type: application/json

{
  "id": "d280f00f-cb6c-4125-a137-41d7d6df4ae7",
  "name": "Evento 3",
  "day": "2025-05-29",
  "startTime": "08:00:00",
  "endTime": "12:00:00",
  "theme": "Tema A",
  "targetAudience": "Público A",
  "mode": "PRESENCIAL",
  "environment": "Auditório",
  "organizer": "Organizador A",
  "resourcesDescription": ["Projetor", "Microfone"],
  "disclosureMethod": "Redes Sociais",
  "relatedSubjects": ["Matemática"],
  "teachingStrategy": "Expositiva",
  "authors": ["Autor A", "Autor B"],
  "courses": ["Course A"],
  "disciplinaryLink": "Disciplina A",
  "location": {
    "name": "Local X",
    "floor": "0"
  },
  "status": "PLANEJADO",
  "administrativeStatus": "NORMAL",
  "priority": "ALTA",
  "cleanupDuration": "PT15M",
  "observation": "Nenhuma"
}

### Deletar um evento
DELETE http://localhost:8080/api/events/{id}
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNkZWZAZXhhbXBsZS5jb20iLCJpYXQiOjE3NDI2NjkwODQsImV4cCI6MTc0Mjc1NTQ4NH0.icukcr4BOE7xiOnV4KiE8pCeXCoxNJD1L0cHlUeVxCw

### Resolver conflito de evento
POST http://localhost:8080/api/events/resolve/{existingEventId}
Content-Type: application/json

{
  "name": "Novo Evento",
  "day": "2025-03-22",
  "startTime": "15:00:00",
  "endTime": "17:00:00",
  "theme": "Tecnologia",
  "priority": "MEDIA",
  "location": { "name": "Sala 102", "floor": "1" }
}

###
POST http://localhost:8080/api/events/resolve/cedb19e7-e2b9-4f31-b48c-7c8c1f94715e
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNkZWZAZXhhbXBsZS5jb20iLCJpYXQiOjE3NDI2NjkwODQsImV4cCI6MTc0Mjc1NTQ4NH0.icukcr4BOE7xiOnV4KiE8pCeXCoxNJD1L0cHlUeVxCw
Content-Type: application/json

{
  "name": "Evento J",
  "day": "2025-04-01",
  "startTime": "07:00:00",
  "endTime": "08:00:00",
  "theme": "Tema A",
  "targetAudience": "Público A",
  "mode": "PRESENCIAL",
  "environment": "Auditório",
  "organizer": "Organizador A",
  "resourcesDescription": ["Projetor", "Microfone"],
  "disclosureMethod": "Redes Sociais",
  "relatedSubjects": ["Matemática"],
  "teachingStrategy": "Expositiva",
  "authors": ["Autor A", "Autor B"],
  "courses": ["Course A"],
  "disciplinaryLink": "Disciplina A",
  "location": {
    "name": "Local X",
    "floor": "0"
  },
  "status": "PLANEJADO",
  "administrativeStatus": "NORMAL",
  "priority": "ALTA",
  "cleanupDuration": "PT15M",
  "observation": "Nenhuma"
}
