# Criar um novo evento
POST http://localhost:8080/api/events
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXN0ZXJAZ21haWwuY29tIiwiaWF0IjoxNzQzNjQzMzAzLCJleHAiOjE3NDM3Mjk3MDN9.4R29sUne741GT0PoZ8JVztJS-YsjUFX5mFUcXTgunNE
Content-Type: application/json

{
  "name": "Evento B",
  "day": "2025-04-02",
  "startTime": "12:00:00",
  "endTime": "15:00:00",
  "theme": "Tecnologia",
  "targetAudience": "Estudantes",
  "mode": "PRESENCIAL",
  "environment": "Auditório",
  "organizer": "Prof. João",
  "resourcesDescription": ["Projetor", "Microfone"],
  "disclosureMethod": "E-mail",
  "relatedSubjects": ["Computação", "Engenharia"],
  "teachingStrategy": "Palestra",
  "authors": ["Prof. João"],
  "courses": ["Arte"],
  "disciplinaryLink": "Informática",
  "location": { "name": "Sala 101", "floor": "0" },
  "observation": "Trazer material de anotação",
  "status": "EM_BREVE",
  "priority": "ALTA",
  "cleanupDuration": "PT30M"
}

### Buscar evento por ID
GET http://localhost:8080/api/events/548e9816-05e8-45e2-b66f-95e89a43b5ae
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNkZWZAZXhhbXBsZS5jb20iLCJpYXQiOjE3NDI3NzczODYsImV4cCI6MTc0Mjg2Mzc4Nn0.Kq9E7J4YPJd0Rlv-De_IouNhgeVuqm1ccwaEFigH2c4

### Buscar todos os eventos
GET http://localhost:8080/api/events
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNkZWZAZXhhbXBsZS5jb20iLCJpYXQiOjE3NDI3NzczODYsImV4cCI6MTc0Mjg2Mzc4Nn0.Kq9E7J4YPJd0Rlv-De_IouNhgeVuqm1ccwaEFigH2c4

### Atualizar um evento existente
POST http://localhost:8080/api/events/resolve-update/dad78626-5023-48cc-88de-b52892908e3b
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNkZWZAZXhhbXBsZS5jb20iLCJpYXQiOjE3NDI5NDUzNjAsImV4cCI6MTc0MzAzMTc2MH0.OAbQva1-Zw5n_j-C0IsY5S_0l52GpAT85IRbHbMB_UU
Content-Type: application/json

{
  "name": "Evento B",
  "day": "2025-04-01",
  "startTime": "08:00:00",
  "endTime": "09:00:00",
  "theme": "Tecnologia",
  "targetAudience": "Estudantes",
  "mode": "PRESENCIAL",
  "environment": "Auditório",
  "organizer": "Prof. João",
  "resourcesDescription": ["Projetor", "Microfone"],
  "disclosureMethod": "E-mail",
  "relatedSubjects": ["Computação", "Engenharia"],
  "teachingStrategy": "Palestra",
  "authors": ["Prof. João"],
  "disciplinaryLink": "Informática",
  "location": { "name": "Sala 101", "floor": "0" },
  "observation": "Trazer material de anotação",
  "status": "EM_BREVE",
  "priority": "ALTA",
  "cleanupDuration": "PT30M"
}



### Deletar um evento
DELETE http://localhost:8080/api/events/{id}
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNkZWZAZXhhbXBsZS5jb20iLCJpYXQiOjE3NDI2NjkwODQsImV4cCI6MTc0Mjc1NTQ4NH0.icukcr4BOE7xiOnV4KiE8pCeXCoxNJD1L0cHlUeVxCw

### Resolver conflito de evento
POST http://localhost:8080/api/events/resolve/{existingEventId}
Content-Type: application/json

{
  "name": "Novo Evento",
  "day": "2025-03-22",
  "startTime": "15:00:00",
  "endTime": "17:00:00",
  "theme": "Tecnologia",
  "priority": "MEDIA",
  "location": { "name": "Sala 102", "floor": "1" }
}

###
POST http://localhost:8080/api/events/resolve/cedb19e7-e2b9-4f31-b48c-7c8c1f94715e
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNkZWZAZXhhbXBsZS5jb20iLCJpYXQiOjE3NDI2NjkwODQsImV4cCI6MTc0Mjc1NTQ4NH0.icukcr4BOE7xiOnV4KiE8pCeXCoxNJD1L0cHlUeVxCw
Content-Type: application/json

{
  "name": "Evento Teste B",
  "day": "2025-03-22",
  "startTime": "06:40:00",
  "endTime": "08:00:00",
  "theme": "Tecnologia",
  "targetAudience": "Estudantes",
  "mode": "IN_PERSON",
  "environment": "Auditório",
  "organizer": "Prof. João",
  "resourcesDescription": ["Projetor", "Microfone"],
  "disclosureMethod": "E-mail",
  "relatedSubjects": ["Computação", "Engenharia"],
  "teachingStrategy": "Palestra",
  "authors": ["Prof. João"],
  "disciplinaryLink": "Informática",
  "location": { "name": "Sala 101", "floor": "1" },
  "observation": "Trazer material de anotação",
  "status": "EM_BREVE",
  "priority": "ALTA",
  "cleanupDuration": "PT30M"
}
