### Criar um evento pendente
POST http://localhost:8080/pending-events
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4OWRmOTllNy0wNzU5LTRiN2YtYTNhMS1kMzYwMTRhMzBlMmYiLCJlbWFpbCI6InJlcXVlc3RlckBnbWFpbC5jb20iLCJyb2xlcyI6WyJSRVFVRVNURVIiXSwiaWF0IjoxNzQzODgyNjYwLCJleHAiOjE3NDM5NjkwNjB9.fQYeFxuFGo5dDHn37vYcQaKLFC7g5yG8aRkfI1kzNjg
Content-Type: application/json

{
  "name": "Workshop de Spring Boot H 4",
  "day": "2025-10-10",
  "startTime": "04:00",
  "endTime": "09:00",
  "theme": "Desenvolvimento Web",
  "targetAudience": "Estudantes e desenvolvedores",
  "mode": "PRESENCIAL",
  "environment": "Zoom",
  "organizer": "Faculdade de Tecnologia",
  "resourcesDescription": ["Computador", "Internet"],
  "disclosureMethod": "Redes sociais e email",
  "relatedSubjects": ["Programação", "Backend"],
  "teachingStrategy": "Aulas práticas",
  "authors": ["João Silva"],
  "courses": ["Engenharia de Software"],
  "disciplinaryLink": "Tecnologia da Informação",
  "location":  { "name": "Sala 101", "floor": "0" },
  "status": "PENDENTE",
  "priority": "ALTA",
  "cleanupDuration": "PT30M",
  "observation": "Levar notebook pessoal"
}

### Buscar todos os eventos pendentes (Apenas MASTER)
GET http://localhost:8080/pending-events
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyYWJjNGQ4Ny1iN2EwLTQ5YzQtYTkzMy02NmY5OTcxNjJjNjQiLCJlbWFpbCI6Im1hc3RlckBnbWFpbC5jb20iLCJyb2xlcyI6WyJNQVNURVIiXSwiaWF0IjoxNzQzODc2NDczLCJleHAiOjE3NDM5NjI4NzN9.fwnKoOBakQlT_8Y1TCdHyGUHAKA5rtb0OZBQx5AffIk

### Buscar eventos pendentes do solicitante (Apenas REQUESTER)
GET http://localhost:8080/pending-events/my-requests
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4OWRmOTllNy0wNzU5LTRiN2YtYTNhMS1kMzYwMTRhMzBlMmYiLCJlbWFpbCI6InJlcXVlc3RlckBnbWFpbC5jb20iLCJyb2xlcyI6WyJSRVFVRVNURVIiXSwiaWF0IjoxNzQzODIwNzAwLCJleHAiOjE3NDM5MDcxMDB9.b9rUCHlISWwekRHm-a6OO7gkvRbdNiuVagLmiAjdUrA

### Aprovar um evento pendente (Apenas MASTER)
POST http://localhost:8080/event-approval/3b6963dd-97a0-457c-8e36-8f0b0eb3f539/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyYWJjNGQ4Ny1iN2EwLTQ5YzQtYTkzMy02NmY5OTcxNjJjNjQiLCJlbWFpbCI6Im1hc3RlckBnbWFpbC5jb20iLCJyb2xlcyI6WyJNQVNURVIiXSwiaWF0IjoxNzQzODc0NDA3LCJleHAiOjE3NDM5NjA4MDd9.OqaZsSYxU0F79BGmCYOVjTNJGStmGbvX1hJJ6IuQmWM

### Rejeitar um evento pendente (Apenas MASTER)
DELETE http://localhost:8080/event-approval/{id}/reject
Authorization: Bearer YOUR_MASTER_TOKEN_HERE

### Deletar um evento pendente (Apenas REQUESTER)
DELETE http://localhost:8080/pending-events/{id}
Authorization: Bearer YOUR_REQUESTER_TOKEN_HERE

###
POST http://localhost:8080/event-approval/49a30f1c-ddad-4755-9039-b14b3bc7efff/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyYWJjNGQ4Ny1iN2EwLTQ5YzQtYTkzMy02NmY5OTcxNjJjNjQiLCJlbWFpbCI6Im1hc3RlckBnbWFpbC5jb20iLCJyb2xlcyI6WyJNQVNURVIiXSwiaWF0IjoxNzQzODgyNzg4LCJleHAiOjE3NDM5NjkxODh9.TAkm5hanE_VN8uSCK1-u7IQwuGL_KrJksNaUhbNiDKU

###
POST http://localhost:8080/event-approval/resolve/6ab1a1b6-bff6-4ce4-b40f-bc580972ddb9/49a30f1c-ddad-4755-9039-b14b3bc7efff
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyYWJjNGQ4Ny1iN2EwLTQ5YzQtYTkzMy02NmY5OTcxNjJjNjQiLCJlbWFpbCI6Im1hc3RlckBnbWFpbC5jb20iLCJyb2xlcyI6WyJNQVNURVIiXSwiaWF0IjoxNzQzODgyNzg4LCJleHAiOjE3NDM5NjkxODh9.TAkm5hanE_VN8uSCK1-u7IQwuGL_KrJksNaUhbNiDKU


###
GET http://localhost:8080/pending-events/my-requests
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4OWRmOTllNy0wNzU5LTRiN2YtYTNhMS1kMzYwMTRhMzBlMmYiLCJlbWFpbCI6InJlcXVlc3RlckBnbWFpbC5jb20iLCJyb2xlcyI6WyJSRVFVRVNURVIiXSwiaWF0IjoxNzQzODA4MzMwLCJleHAiOjE3NDM4OTQ3MzB9.aEWOaed22YHfhgWAR3_WoueA7A_e9I7wTBpp73irecY
###

### Criar um evento pendente
POST http://localhost:8080/pending-events
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4OWRmOTllNy0wNzU5LTRiN2YtYTNhMS1kMzYwMTRhMzBlMmYiLCJlbWFpbCI6InJlcXVlc3RlckBnbWFpbC5jb20iLCJyb2xlcyI6WyJSRVFVRVNURVIiXSwiaWF0IjoxNzQzODExMDg1LCJleHAiOjE3NDM4OTc0ODV9.673o8RcH9gXSCBy7kDsG_nb0oYkv2Zl1LjVTQjxCqS0
Content-Type: application/json

{
  "name": "Workshop de Spring Boot A",
  "day": "2025-11-09",
  "startTime": "18:00",
  "endTime": "19:00",
  "theme": "Desenvolvimento Web",
  "targetAudience": "Estudantes e desenvolvedores",
  "mode": "PRESENCIAL",
  "environment": "Zoom",
  "organizer": "Faculdade de Tecnologia",
  "resourcesDescription": ["Computador", "Internet"],
  "disclosureMethod": "Redes sociais e email",
  "relatedSubjects": ["Programação", "Backend"],
  "teachingStrategy": "Aulas práticas",
  "authors": ["João Silva"],
  "courses": ["Engenharia de Software"],
  "disciplinaryLink": "Tecnologia da Informação",
  "location":  { "name": "Sala 101", "floor": "0" },
  "status": "PENDENTE",
  "priority": "ALTA",
  "cleanupDuration": "PT30M",
  "observation": "Levar notebook pessoal"
}
